version: "2"

services:

  iotex-core:
    image: iotex/iotex-core:testnet 
    volumes:
      - ./config.yaml:/etc/iotex/config_local_fullnode.yaml:ro
      - ./db:/go/src/github.com/iotexproject/iotex-core/db:rw
    ports:
      - "30555:30555"
      - "6060:6060"
      - "8080:8080"
  
  iotex-wallet:
    image: fabryprog/iotex-wallet:testnet

  iotex-explorer:
    image: fabryprog/iotex-explorer
    ports:
      - "4004:4004"
    environment:
      - IOTEX_CORE_URL=http://iotex-core:14004/
      - IOTEX_WALLET_URL=iotex-wallet:42124
